image: node:wheezy

cache:
  paths:
  - node_modules/

stages:
  - test

test_lint:
  stage: test
  script:
  - npm i -g eslint
  - npm i
  - npm run lint
  tags:
<<<<<<< 5daf3a8a674a44f9b7dee0a3ea2281fa092b45b1
    - docker
=======
    - docker
>>>>>>> coding
