version: '2'
services:
  node:
    build: .
    environment:
      NODE_ENV: development
      PORT: "8080"
      HOST: localhost
      # Parse server
      VERBOSE:
      APP_ID:
      MASTER_KEY:
      DASHBOARD_AUTH: admin:admin
      SESSION_LENGTH:
      # Database
      DATABASE_URI: mongodb://mongo:27017/dev
      # AWS S3
      S3_ACCESS_KEY:
      S3_SECRET_KEY:
      S3_BUCKET:
      S3_BUCKET_PREFIX:
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    links:
      # - redis
      - mongo
  # redis:
  #   image: redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/backup:/data/backup
