version: '2'
services:
  node:
    build: .
    environment:
      - APP_ID=oss-f8-app-2016
      - DASHBOARD_AUTH=admin:admin
      - DATABASE_NAME=dev
      - DATABASE_URI=mongodb://mongo:27017/dev
      - HOST=localhost
      - MASTER_KEY=myMasterKey
      - NODE_ENV=development
      - PM2_WATCH=true
      - PORT=8080
      - S3_ACCESS_KEY=AKIAIR4HJZERLDFCYQBQ
      - S3_BUCKET=ecolab-server
      - S3_BUCKET_PREFIX=
      - S3_SECRET_KEY=G3LSriuivIJ0GFB6x8im/9BlsFUWjaN4uMxhe1e3
      - SESSION_LENGTH=2592000
      - VERBOSE=
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    links:
      # - redis
      - mongo
  # redis:
  #   image: redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/data/db:/data/db
      - ./data/backup:/backup