version: '2'
services:
  web:
    build: .
    environment:
      NODE_ENV: development
      SERVER_PORT: "8080"
      SERVER_HOST: localhost
      # Parse server
      # VERBOSE: 0
      APP_ID:
      MASTER_KEY:
      DASHBOARD_AUTH: admin:admin
      SESSION_LENGTH:
      # Database
      DATABASE_URI: mongodb://mongo:27017/dev
      # AWS S3
      S3_ACCESS_KEY: AKIAIR4HJZERLDFCYQBQ
      S3_SECRET_KEY: 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
      S3_BUCKET: ecolab-server
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    links:
      # - redis
      - mongo
  # redis:
  #   image: redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"