version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src
    links:
      # - redis
      - mongo
  # redis:
  #   image: redis
  mongo:
    image: mongo